### ISSUE TITLE
[BUG]: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by A1X5H04** [inokawa/rich-textarea#156]
**Describe the bug**
This is a internal bug from library that is related to refs, here's an error: 
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? 


Check the render method of 'SlotClone'.
    at RichTextArea (...)
```

**To Reproduce**
Create some components from the demo, mentions etc

**Expected behavior**
The warning should be resolved

**Platform:**
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Version of this package: ^0.26.2

**Additional context**
*Not available*

**Comment by inokawa** [comment]
Could you make a minimal reproduction? It's not reproduced.
