### ISSUE TITLE
The `rangeAtIndex` throws an `IndexSizeError` error

### ISSUE THREAD

**Issue by uonr** [inokawa/rich-textarea#160]
**Describe the bug**
Sometimes the library will throw `IndexSizeError`.

```
IndexSizeError
Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (3).
```
Here's where the error occurred https://github.com/inokawa/rich-textarea/blob/main/src/vendor/range-at-index.js#L47

Called by https://github.com/inokawa/rich-textarea/blob/main/src/input.tsx#L270 and https://github.com/inokawa/rich-textarea/blob/main/src/textarea.tsx#L247

I haven't set selection in my code, I don't know why it's causing this error, it could also be a browser bug, but it looks like you can avoid a component crash by simply checking the `selectionStart`.

**To Reproduce**
I only have the bug report, not the actual reproduction.

**Expected behavior**
Check the parameters, or catch an error so that the component does not crash.

<img width="370" alt="图片" src="https://github.com/user-attachments/assets/f34269bf-3d78-48b4-96ad-034721935534">

**Platform:**
- Safari 17.5
- Chrome 128.0

**Additional context**

**Comment by inokawa** [comment]
https://github.com/slab/quill/issues/3080#issuecomment-652000347
https://github.com/ueberdosis/tiptap/issues/954#issuecomment-788133825
