### ISSUE TITLE
how can i disable New Line in Textarea when Pressed ENTER

### ISSUE THREAD

**Issue by wuhonglei** [inokawa/rich-textarea#20]
**Is your feature request related to a problem? Please describe.**
In our businebusiness, we need to display the rich-textarea in single line (just like input), how can i disable the enter key to prevent line break

<img width="626" alt="image" src="https://user-images.githubusercontent.com/12020551/165422626-145ce1a9-5354-44b0-9cce-717f7e672c2d.png">

demo: 

https://codesandbox.io/s/dark-voice-5sghsl?file=/src/App.js

**Describe the solution you'd like**
when i click the enter key, i wish the onChange event will not be triggerd and the caret position will not change

**Describe alternatives you've considered**
currently, i handle this problem in the onChange function, to replace any line break \n to empty space, but the caret will move to the last position

**Additional context**

**Comment by inokawa** [comment]
Hi, you can cancel enter key with onKeyDown handler like this

```tsx
   <RichTextarea
      value={value}
      onChange={(e) => handleChange(e.target.value)}
      onKeyDown={(e) => {
        if (e.key === "Enter") {
          e.preventDefault();
        }
      }}
    >
```

**Comment by wuhonglei** [comment]
> 

thanks, it works.

**Comment by wuhonglei** [comment]
for the same situation, in the single line mode, when i paste content which contains line break, i need to replace the line break with empty string and set the caret to the new position where the new content end. currently i do not how to get the end end position of caret.

**Comment by wuhonglei** [comment]
another question, in the single line mode, when i input text overflow the width of the deepest div container, the char of the right edge can also be visible,  i already set the right padding of div.


https://user-images.githubusercontent.com/12020551/165496529-4fe8abdb-c3a9-4a37-a159-3231ec78a36d.mov

**Comment by wuhonglei** [comment]
> for the same situation, in the single line mode, when i paste content which contains line break, i need to replace the line break with empty string and set the caret to the new position where the new content end. currently i do not how to get the end end position of caret.
> 
>  iShot2022-04-27_18.20.03.mov

i have solve ths problem，the step is below:

bind onPaste event listener on RichTextarea, the same as onKeyDown, when i detect the line break in the clipboardData, onvoke `e.preventDefault();` and then use setRangeText to insert the clipboardData which has beed removed line break.
