### ISSUE TITLE
Need apis for addonAfter btns, especially when wrap="off" (just have 1 row)

### ISSUE THREAD

**Issue by ScarlettKK** [inokawa/rich-textarea#36]
**Background:**
My team is using rich-textarea in our project, and we meet some problems when we just need one line to input in <RichTextarea />(wrap="off").

As the following picture, we also want to add some functional btns like addonAfter after the <RichTextarea />, as well as keep it in one line and do not wrap.

![image](https://user-images.githubusercontent.com/47051897/196889581-6c5e8f0d-4cfc-45af-b9a8-b5e53ce949d7.png)

**But here is the problem:**

The input content cursor and scroll will not stop at the position where we set the padding-right, but overflow until the end, so that some parts of the input content is covered by addonAfter.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/47051897/196890858-d3c96450-4597-41e7-a441-fcad35daa703.png">

![WechatIMG13](https://user-images.githubusercontent.com/47051897/196892856-78606fce-8f3c-42dd-b6ba-9b35df3f70bd.jpeg)

<img width="332" alt="image" src="https://user-images.githubusercontent.com/47051897/196890899-846b744c-2d11-4271-afae-1572805b43da.png">

**Hope solution**
when there is only one line for <RichTextarea /> without wrap, we want to change the inside component to *Input* rather than *Textarea* automatically, or you can expose apis for us to change the inner component or add addonAfter.

Thanks a lot~

**Comment by ScarlettKK** [comment]
Thanks 😄

**Comment by inokawa** [comment]
I released experimental `RichInput` component in `0.18.0`.
It may have some bugs and the API may change.

**Comment by inokawa** [comment]
Close for now.
Feel free to reopen if you have some problems
