### ISSUE TITLE
Doesn't work with `box-sizing: border-box` styles

### ISSUE THREAD

**Issue by cheeaun** [inokawa/rich-textarea#56]
**Describe the bug**
The `textarea` styles don't work properly with `box-sizing: border-box` styles.

**To Reproduce**
Apply `box-sizing: border-box` and `padding: 10px` (or any number) to `textarea`. Width and height calculation becomes wrong.

**Expected behavior**
Width and height calculation should be correct, even when `box-sizing: border-box` is applied.

**Platform:**
 - OS: macOS 13.1 Ventura
 - Browser: Chrome 108
 - Version of this package: 0.19.4

**Additional context**
It's pretty common for sites now that have this style:

```css
*, *:before, *:after { box-sizing: border-box }
```

So, the calculation need to work on both the `textarea` _and_ generated `div`s from this package. I've made a demo here: **https://stackblitz.com/edit/vitejs-vite-vmbnhu?file=src/App.jsx**

[<img width="396" alt="Screenshot 2023-01-03 at 10 51 08 PM" src="https://user-images.githubusercontent.com/2296/210381372-10603646-e173-4f1c-8101-c767c789ad8a.png">](https://stackblitz.com/edit/vitejs-vite-vmbnhu?file=src/App.jsx)

The `div`'s dimensions become completely wrong:

<img width="343" alt="Screenshot 2023-01-03 at 10 54 00 PM" src="https://user-images.githubusercontent.com/2296/210381781-ca1c6d16-ab5b-40ee-96be-e0479324a4cb.png">

**Comment by inokawa** [comment]
It was fixed in`0.19.5`.
Thank you.

**Comment by cheeaun** [comment]
@inokawa thanks for the very fast fix! 🤯
