### ISSUE TITLE
Setting an initial height smaller than 48px

### ISSUE THREAD

**Issue by victorforissier** [inokawa/rich-textarea#61]
**Can't set the initial height when using autoHeight**
Can't use TextArea as input that expands if someone writes past 1 line. It would be nice to set the min text area height so we can have an input that's 24px in width instead of the default 48px. And then still keep the autoHeight prop.

**Describe the solution you'd like**
A initHeight prop, to set when using the autoHeight prop.

**Describe alternatives you've considered**
Forking the repo.

**Comment by inokawa** [comment]
@victorforissier 
Hi, you can achieve 1 line auto-resized textarea with `rows={1}` attr.
```tsx
<RichTextarea
  style={anyStyle}
  value={anyValue}
  rows={1}
  autoHeight
  ...
>
```
