### ISSUE TITLE
Foreground and background text misaligned on fontSize change

### ISSUE THREAD

**Issue by idroz** [inokawa/rich-textarea#62]
**Describe the bug**
Dynamically increasing/reducing font size causes foreground and background text of the text area to be misaligned

**To Reproduce**
```
const [fontSize, setFontSize] = useState(1.5);
<RichTextarea
            id="textarea"
            style={{
              fontSize: `${fontSize}rem`,
            }}
</RichTextarea>
```

**Expected behavior**
Changing font size will keep the foreground and background text elements aligned

**Platform:**
 - OS:  MacOS
 - Browser: Safari, Edge
 - Version of this package: ^0.19.5

**Additional context**
You can see the misalignment between foreground and background text using highlight in a screenshot below.

<img width="970" alt="Screenshot 2023-02-22 at 08 51 25" src="https://user-images.githubusercontent.com/12413294/220569760-0e01241d-7ccd-4697-9afd-bfc27302bc61.png">

**Comment by inokawa** [comment]
It is not reproduced in my envirionment with your code.

May be it is affected by global style or something else, if I'm not mistaken.

**Comment by idroz** [comment]
Thanks very much for the reply.

Yes, the issue was that font size was set in `rem`. Switching to `px` seems to have resolved this issue.
