### ISSUE TITLE
Add mode to use contenteditable as io

### ISSUE THREAD

**Issue by inokawa** [inokawa/rich-textarea#74]
**Is your feature request related to a problem? Please describe.**

Using textarea as io is suitable for most case, however there are several things impossible to do with textarea, such as changing font-size or adding padding to words.

**Describe the solution you'd like**

Add option to use contenteditable instead of textarea.

**Describe alternatives you've considered**

Nothing.

**Additional context**

Nothing.

**Comment by aeharding** [comment]
I would love this. I [discussed this a couple months ago, lamenting how nothing like this exists for the web](https://github.com/aeharding/voyager/discussions/620#discussioncomment-6663131). This library gets close — but it would be great to have the ability to change font size and font weight as well.

**Comment by inokawa** [comment]
https://github.com/yuneco/canvas-draw-styled-text

**Comment by inokawa** [comment]
https://github.com/w3c/csswg-drafts/issues/4603

**Comment by A1X5H04** [comment]
When will this be available, I am waiting for it for so long..

**Comment by inokawa** [comment]
Hi, I've been experimenting with contenteditable recently to make a new library. Please post here if you have something necessary for your usecase, to judge which features are needed for the MVP.

**Comment by inokawa** [comment]
Closing because it is supported in the other package. The repo will be available soon...
https://github.com/inokawa/edix
