### ISSUE TITLE
On some mobile browsers, cursor is misaligned from text

### ISSUE THREAD

**Issue by bpevs** [inokawa/rich-textarea#95]
**Describe the bug**
Basically as the title/screenshots show, the cursor is not showing up where the text is.  The 2nd screenshot shows what it looks like when I try to highlight the text, so I wonder if there's a just particular style being applied or blocked for some browser contexts that mess with it? 

**To Reproduce**
Weirdly, I'm not seeing this on Chrome and Firefox on android or on desktop; just the internal browser (like when you click a link to a webview from an app). I was also seeing it on Mull (a "privacy" browser based on Firefox), before I updated to latest. So maybe it's a browser issue that's being patched?  But figured I'd make an issue, just in case it reveals something to prevent issues in the future.

**Expected behavior**
When you type, the text should appear where the cursor is. When clicking on text, the cursor should appear at that text location.

**Platform:**
 - OS: Android 
 - Browser: Webview, Mull 109.1.1 (based on Firefox 112)
 - Version of this package: [0.22.3]

**Additional context**
So it works on FF 115.2.1, but not on Mull, which is based on FF 112

Screenshot viewing [inokawa.github.io/rich-textarea/](https://inokawa.github.io/rich-textarea/)
![Screenshot_20230723-140524_Mull](https://github.com/inokawa/rich-textarea/assets/8182843/796a3c77-4b3c-47dd-9b14-941215cea37b)

![Screenshot_20230723-142244_internal](https://github.com/inokawa/rich-textarea/assets/8182843/38e76d2f-5796-4e6d-b1a7-b32a0f15761b)

**Comment by inokawa** [comment]
@bpevs 
Could you give me information about styles applied to textarea and div wrapping highlighted texts?

This library extracts styles from transparent textarea with `window.getComputedStyle` and applys them to div wrapping visible texts. So what I suspects is the font related styles has difference between textarea and div for some reason.

And as described in https://github.com/inokawa/rich-textarea/issues/62#issuecomment-1440981096 , this lib may have bugs under some specific styles.

<img width="656" alt="スクリーンショット 2023-07-24 10 20 51" src="https://github.com/inokawa/rich-textarea/assets/48897392/cb80a98c-66fc-4a49-b780-9325a5ccf091">

**Comment by bpevs** [comment]
sorrysorry I'm having trouble opening the devtools for the context where this is happening...  I could try to create public repo to replicate behavior, but currently running webview within [tauri-android alpha](https://tauri.app/blog/2023/03/20/tauri-2-0-0-alpha-4), so not sure how useful that would be, since it'd be annoying to run, and is pretty niche.

I did try to remove everything that I could, and I was still seeing this behavior, though.

(oops sorry, ignore theme function, it isn't doing anything here)
<img width="658" alt="Screenshot 2023-07-24 at 4 00 48 PM" src="https://github.com/inokawa/rich-textarea/assets/8182843/48db5479-9057-4bba-8a70-388091de8c12">

![Screenshot_20230724-155734_app](https://github.com/inokawa/rich-textarea/assets/8182843/55a4196c-3116-4b49-a45a-88a68b62ff2b)

**NOTE: these computed styles are WORKING in the context where the devtools are running. It looks correct here:**
<img width="1145" alt="Screenshot 2023-07-24 at 3 59 57 PM" src="https://github.com/inokawa/rich-textarea/assets/8182843/eb027693-dfd2-4274-bf58-00ee341b7843">

**Comment by inokawa** [comment]
I've noticed that `text-size-adjust` is not supported in Firefox on android without -moz prefix.
I'm not sure that is related to this issue but it was necessary style in browsers on iOS.
